// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetConfigApiPyConfigGetData, GetConfigApiPyConfigGetResponses, PostCompletionsApiPyCompletionsPostData, PostCompletionsApiPyCompletionsPostErrors, PostCompletionsApiPyCompletionsPostResponses, UpdateConfigApiPyConfigPostData, UpdateConfigApiPyConfigPostErrors, UpdateConfigApiPyConfigPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Config
 *
 * Get the current YAML configuration
 */
export const getConfigApiPyConfigGet = <ThrowOnError extends boolean = false>(options?: Options<GetConfigApiPyConfigGetData, ThrowOnError>) => (options?.client ?? client).get<GetConfigApiPyConfigGetResponses, unknown, ThrowOnError>({ url: '/api/py/config', ...options });

/**
 * Update Config
 *
 * Update the YAML configuration
 */
export const updateConfigApiPyConfigPost = <ThrowOnError extends boolean = false>(options: Options<UpdateConfigApiPyConfigPostData, ThrowOnError>) => (options.client ?? client).post<UpdateConfigApiPyConfigPostResponses, UpdateConfigApiPyConfigPostErrors, ThrowOnError>({
    url: '/api/py/config',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post Completions
 *
 * Get completions for the current cursor position
 */
export const postCompletionsApiPyCompletionsPost = <ThrowOnError extends boolean = false>(options: Options<PostCompletionsApiPyCompletionsPostData, ThrowOnError>) => (options.client ?? client).post<PostCompletionsApiPyCompletionsPostResponses, PostCompletionsApiPyCompletionsPostErrors, ThrowOnError>({
    url: '/api/py/completions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
