// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CompletionItem
 */
export type CompletionItem = {
    /**
     * Label
     */
    label: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Inserttext
     */
    insertText: string;
    /**
     * Documentation
     */
    documentation?: string | null;
};

/**
 * CompletionRequest
 */
export type CompletionRequest = {
    /**
     * Line
     */
    line: string;
    /**
     * Cursor Position
     */
    cursor_position: number;
    /**
     * Full Content
     */
    full_content: string;
    /**
     * Line Number
     */
    line_number: number;
};

/**
 * CompletionResponse
 */
export type CompletionResponse = {
    /**
     * Completions
     */
    completions: Array<CompletionItem>;
};

/**
 * Config
 */
export type Config = {
    server: ServerConfig;
    logging: LoggingConfig;
};

/**
 * ConfigResponse
 */
export type ConfigResponse = {
    config: Config;
    /**
     * Yaml Content
     */
    yaml_content: string;
};

/**
 * ConfigUpdate
 */
export type ConfigUpdate = {
    /**
     * Yaml Content
     */
    yaml_content: string;
};

/**
 * ConfigUpdateResponse
 */
export type ConfigUpdateResponse = {
    /**
     * Success
     */
    success: boolean;
    config: Config;
    /**
     * Yaml Content
     */
    yaml_content: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoggingConfig
 */
export type LoggingConfig = {
    /**
     * Level
     */
    level: 'debug' | 'info' | 'warn' | 'error';
    /**
     * File
     */
    file: string;
};

/**
 * ServerConfig
 */
export type ServerConfig = {
    /**
     * Host
     */
    host: string;
    /**
     * Port
     */
    port: number;
    /**
     * Use Ssl
     */
    use_ssl: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetConfigApiPyConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/py/config';
};

export type GetConfigApiPyConfigGetResponses = {
    /**
     * Successful Response
     */
    200: ConfigResponse;
};

export type GetConfigApiPyConfigGetResponse = GetConfigApiPyConfigGetResponses[keyof GetConfigApiPyConfigGetResponses];

export type UpdateConfigApiPyConfigPostData = {
    body: ConfigUpdate;
    path?: never;
    query?: never;
    url: '/api/py/config';
};

export type UpdateConfigApiPyConfigPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConfigApiPyConfigPostError = UpdateConfigApiPyConfigPostErrors[keyof UpdateConfigApiPyConfigPostErrors];

export type UpdateConfigApiPyConfigPostResponses = {
    /**
     * Successful Response
     */
    200: ConfigUpdateResponse;
};

export type UpdateConfigApiPyConfigPostResponse = UpdateConfigApiPyConfigPostResponses[keyof UpdateConfigApiPyConfigPostResponses];

export type PostCompletionsApiPyCompletionsPostData = {
    body: CompletionRequest;
    path?: never;
    query?: never;
    url: '/api/py/completions';
};

export type PostCompletionsApiPyCompletionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostCompletionsApiPyCompletionsPostError = PostCompletionsApiPyCompletionsPostErrors[keyof PostCompletionsApiPyCompletionsPostErrors];

export type PostCompletionsApiPyCompletionsPostResponses = {
    /**
     * Successful Response
     */
    200: CompletionResponse;
};

export type PostCompletionsApiPyCompletionsPostResponse = PostCompletionsApiPyCompletionsPostResponses[keyof PostCompletionsApiPyCompletionsPostResponses];
